
isEmpty(PERFPARSER_APP_DESTDIR): PERFPARSER_APP_DESTDIR = $$shadowed($$PWD)/bin
isEmpty(PERFPARSER_INSTALLDIR_PREFIX): PERFPARSER_INSTALLDIR_PREFIX = /usr/local
isEmpty(PERFPARSER_APP_INSTALLDIR): PERFPARSER_APP_INSTALLDIR = $$PERFPARSER_INSTALLDIR_PREFIX/bin

isEmpty(PERFPARSER_ELFUTILS_BACKENDS_INSTALLDIR):!isEmpty(PERFPARSER_ELFUTILS_INSTALLDIR) {
    PERFPARSER_ELFUTILS_BACKENDS_INSTALLDIR = $$PERFPARSER_ELFUTILS_INSTALLDIR/elfutils
}
